sudo: required
services:
  - docker

before_install:
  - docker build -t oniharnantyo/learn-docker-react-ci -f Dockerfile.dev .

script:
  - docker run -e CI=true oniharnantyo/learn-docker-react-ci npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-005651531244"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
