sudo: required
services:
  - docker

before_install:
  - docker build -t oniharnantyo/learn-docker-react-ci -f Dockerfile.dev .

script:
  - docker run -e CI=true oniharnantyo/learn-docker-react-ci npm run test